#!/usr/bin/env python3
"""
convert_polar_f32_tflite.py
----------------------------
Convert the trained Keras MLP to a pure Float32 TFLite model (NO quantization)
and generate C headers for ESP32-S3 deployment.

Outputs:
    polar_model_f32.tflite   - Float32 TFLite flatbuffer
    polar_model_data.h       - C byte-array header (alignas(16))
    polar_norm_params.h      - C normalization constants header
"""

import os
import json
import numpy as np
import tensorflow as tf

# ═══════════════════════════════════════════════════════════════════════════
#  STEP 1 — Convert SavedModel to Float32 TFLite (NO quantization)
# ═══════════════════════════════════════════════════════════════════════════

print("=" * 60)
print("  STEP 1: Convert SavedModel -> Float32 TFLite")
print("=" * 60)

converter = tf.lite.TFLiteConverter.from_saved_model("polar_mlp_f32_saved/")
# Pure Float32 pass-through — no optimizations, no quantization
tflite_model = converter.convert()

tflite_path = "polar_model_f32.tflite"
with open(tflite_path, "wb") as f:
    f.write(tflite_model)

tflite_size = len(tflite_model)
print(f"Saved: {tflite_path}")
print(f"Size:  {tflite_size} bytes ({tflite_size / 1024:.1f} KB)")

# ═══════════════════════════════════════════════════════════════════════════
#  STEP 2 — Validate conversion accuracy (Keras vs TFLite)
# ═══════════════════════════════════════════════════════════════════════════

print("\n" + "=" * 60)
print("  STEP 2: Validate Conversion Accuracy")
print("=" * 60)

# Load validation data
X_val = np.load("X_val.npy")
y_val = np.load("y_val.npy")

# Flatten (N, 5, 5) -> (N, 25)
X_val_flat = X_val.reshape(X_val.shape[0], -1).astype(np.float32)
N = X_val_flat.shape[0]

# --- Keras inference ---
keras_model = tf.keras.models.load_model("polar_mlp_f32.keras")
keras_preds = keras_model.predict(X_val_flat, verbose=0)

# --- TFLite inference ---
interpreter = tf.lite.Interpreter(model_path=tflite_path)
interpreter.allocate_tensors()

input_details  = interpreter.get_input_details()
output_details = interpreter.get_output_details()

tflite_preds = np.zeros((N, 2), dtype=np.float32)
for i in range(N):
    interpreter.set_tensor(input_details[0]["index"],
                           X_val_flat[i:i+1])
    interpreter.invoke()
    tflite_preds[i] = interpreter.get_tensor(output_details[0]["index"])[0]

# --- Compare ---
diff = np.abs(keras_preds - tflite_preds)
max_diff_r     = diff[:, 0].max()
mean_diff_r    = diff[:, 0].mean()
max_diff_theta = diff[:, 1].max()
mean_diff_theta = diff[:, 1].mean()
max_diff_overall = diff.max()

print(f"\n=== CONVERSION VALIDATION ===")
print(f"Samples compared: {N}")
print(f"Output 0 (r_norm):     max diff = {max_diff_r:.2e}    mean diff = {mean_diff_r:.2e}")
print(f"Output 1 (theta_norm): max diff = {max_diff_theta:.2e}    mean diff = {mean_diff_theta:.2e}")

if max_diff_overall > 1e-5:
    print("WARNING: Conversion introduced significant error. Investigate.")
    conversion_note = f"max diff = {max_diff_overall:.2e} (WARNING)"
else:
    print("PASS: Conversion is lossless within floating-point precision.")
    conversion_note = f"max diff = {max_diff_overall:.2e} (lossless)"

# ═══════════════════════════════════════════════════════════════════════════
#  STEP 3 — Generate C header: polar_model_data.h
# ═══════════════════════════════════════════════════════════════════════════

print("\n" + "=" * 60)
print("  STEP 3: Generate polar_model_data.h")
print("=" * 60)

model_header_path = "polar_model_data.h"

with open(tflite_path, "rb") as f:
    raw_bytes = f.read()

# Format as hex array, 12 bytes per line
hex_lines = []
for i in range(0, len(raw_bytes), 12):
    chunk = raw_bytes[i:i+12]
    hex_str = ", ".join(f"0x{b:02x}" for b in chunk)
    hex_lines.append(f"    {hex_str},")

# Remove trailing comma from last line
if hex_lines:
    hex_lines[-1] = hex_lines[-1].rstrip(",")

hex_body = "\n".join(hex_lines)

header_content = f"""\
#ifndef POLAR_MODEL_DATA_H
#define POLAR_MODEL_DATA_H

// Auto-generated by convert_polar_f32_tflite.py
// Model size: {tflite_size} bytes
// Conversion validation: {conversion_note}

alignas(16) const unsigned char polar_model_tflite[] = {{
{hex_body}
}};
const unsigned int polar_model_tflite_len = {tflite_size};

#endif
"""

with open(model_header_path, "w") as f:
    f.write(header_content)

model_header_size = os.path.getsize(model_header_path)
print(f"Saved: {model_header_path} ({model_header_size} bytes)")

# ═══════════════════════════════════════════════════════════════════════════
#  STEP 4 — Generate C header: polar_norm_params.h
# ═══════════════════════════════════════════════════════════════════════════

print("\n" + "=" * 60)
print("  STEP 4: Generate polar_norm_params.h")
print("=" * 60)

with open("norm_params.json") as f:
    norm = json.load(f)

norm_header_content = f"""\
#ifndef POLAR_NORM_PARAMS_H
#define POLAR_NORM_PARAMS_H

// Auto-generated by convert_polar_f32_tflite.py
// Normalization: normalized = (value - MIN) / (MAX - MIN)
// Denormalization: value = normalized * (MAX - MIN) + MIN

// --- Physical bounds used during training ---
#define R_MIN_M        {norm['R_MIN_M']:.1f}f
#define R_MAX_M        {norm['R_MAX_M']:.1f}f
#define THETA_MIN_DEG  {norm['THETA_MIN_DEG']:.1f}f
#define THETA_MAX_DEG  {norm['THETA_MAX_DEG']:.1f}f

// --- Sliding window parameters ---
#define WINDOW_SIZE    {norm['WINDOW_SIZE']}
#define NUM_FEATURES   {norm['NUM_FEATURES']}

// --- Feature order within each window row ---
// [{', '.join(norm['features'])}]

// --- Label order ---
// [{', '.join(norm['labels'])}]

#endif
"""

norm_header_path = "polar_norm_params.h"
with open(norm_header_path, "w") as f:
    f.write(norm_header_content)

norm_header_size = os.path.getsize(norm_header_path)
print(f"Saved: {norm_header_path} ({norm_header_size} bytes)")

# ═══════════════════════════════════════════════════════════════════════════
#  STEP 5 — Final verification printout
# ═══════════════════════════════════════════════════════════════════════════

print("\n" + "=" * 60)
print("  STEP 5: Final Verification")
print("=" * 60)

print(f"\n=== FILES GENERATED ===")
print(f"polar_model_f32.tflite  -- {tflite_size} bytes ({tflite_size / 1024:.1f} KB)")
print(f"polar_model_data.h      -- {model_header_size} bytes")
print(f"polar_norm_params.h     -- {norm_header_size} bytes")

print(f"\n=== TFLITE MODEL DETAILS ===")
print(f"Input tensor:  shape={input_details[0]['shape']}  dtype={input_details[0]['dtype']}")
print(f"Output tensor: shape={output_details[0]['shape']}  dtype={output_details[0]['dtype']}")

first_8 = raw_bytes[:8]
hex_display = " ".join(f"0x{b:02x}" for b in first_8)
print(f"\n=== FIRST BYTES CHECK ===")
print(f"First 8 bytes of .tflite: {hex_display}")
print(f"(Should start with 0x20 0x00 0x00 0x00 for valid TFLite FlatBuffer,")
print(f" or 0x1c 0x00 0x00 0x00 depending on TF version -- both are valid)")

print("\n[OK] All done. Ready for ESP32-S3 deployment.")
