#ifndef POLAR_NORM_PARAMS_H
#define POLAR_NORM_PARAMS_H

// Auto-generated by convert_polar_f32_tflite.py
// Normalization: normalized = (value - MIN) / (MAX - MIN)
// Denormalization: value = normalized * (MAX - MIN) + MIN

// --- Physical bounds used during training ---
#define R_MIN_M        0.0f
#define R_MAX_M        6.0f
#define THETA_MIN_DEG  -60.0f
#define THETA_MAX_DEG  60.0f

// --- Sliding window parameters ---
#define WINDOW_SIZE    5
#define NUM_FEATURES   5

// --- Feature order within each window row ---
// [radar_r_norm, radar_theta_norm, radar_fresh, wifi_r_norm, wifi_fresh]

// --- Label order ---
// [gt_r_norm, gt_theta_norm]

#endif
